# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

name: CI
on:
  push:
    paths-ignore:
      - '*.md'
    branches:
      - '*'
    tags:
      - v[0-9]+
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - main
env:
  IMAGE_NAME: yacgroup/yacguide-build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=match,pattern=v(.*),group=1
            type=ref,event=pr
      - name: Login to Docker Hub
        if: ${{ github.ref_type == 'tag' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
